-- orders table creation
DROP TABLE IF EXISTS ORDERS;

CREATE TABLE IF NOT EXISTS ORDERS (ORDER_ID SERIAL PRIMARY KEY, DATE DATE, TIME TIME);

-- details table creation
DROP TABLE IF EXISTS ORDER_DETAILS;

CREATE TABLE IF NOT EXISTS ORDER_DETAILS (
	ORDER_DETAILS_ID INT PRIMARY KEY NOT NULL,
	ORDER_ID INT NOT NULL,
	PIZZA_ID VARCHAR(25),
	QUANTITY INT NOT NULL
);

-- pizza types table creation
DROP TABLE IF EXISTS PIZZA_TYPES;

CREATE TABLE IF NOT EXISTS PIZZA_TYPES (
	PIZZA_TYPE_ID VARCHAR(30),
	NAME VARCHAR(50) NOT NULL,
	CATEGORY VARCHAR(50),
	INGREDIENTS TEXT
);

-- pizzas table creation
DROP TABLE IF EXISTS PIZZAS;

CREATE TABLE IF NOT EXISTS PIZZAS (
	PIZZA_ID VARCHAR(30),
	PIZZA_TYPE_ID VARCHAR(20),
	SIZE VARCHAR(50),
	PRICE DECIMAL(5, 2)
);

-- import 1table
COPY ORDERS (ORDER_ID, DATE, TIME)
FROM
	'J:\Pizza analysis\pizza_sales\orders.csv' CSV HEADER;

-- import 2table
COPY ORDER_DETAILS (ORDER_DETAILS_ID, ORDER_ID, PIZZA_ID, QUANTITY)
FROM
	'J:\Pizza analysis\pizza_sales\order_details.csv' CSV HEADER;

-- import 3table
COPY PIZZA_TYPES (PIZZA_TYPE_ID, NAME, CATEGORY, INGREDIENTS)
FROM
	'J:\Pizza analysis\pizza_sales\pizza_types.csv' DELIMITER ',' CSV HEADER ENCODING 'WIN1252';

-- import 4table
COPY PIZZAS (PIZZA_ID, PIZZA_TYPE_ID, SIZE, PRICE)
FROM
	'J:\Pizza analysis\pizza_sales\pizzas.csv' CSV HEADER;

-- runs all tables
-- orders table
SELECT
	*
FROM
	ORDERS;

-- order details table
SELECT
	*
FROM
	ORDER_DETAILS;

-- pizza type table
SELECT
	*
FROM
	PIZZA_TYPES;

-- pizzas table
SELECT
	*
FROM
	PIZZAS;

-- Retrieve the total number of orders placed.
SELECT
	COUNT(ORDER_ID) AS TOTAL_ORDERS_PLACED
FROM
	ORDERS;

-- Calculate the total revenue generated from pizza sales.
SELECT
	ROUND(SUM(OD.QUANTITY * PS.PRICE), 2) AS TOTAL_REVENUE
FROM
	ORDER_DETAILS AS OD
	JOIN PIZZAS AS PS ON OD.PIZZA_ID = PS.PIZZA_ID;

-- Identify the highest-priced pizza.
SELECT
	PT.NAME,
	MAX(PS.PRICE)
FROM
	PIZZA_TYPES AS PT
	JOIN PIZZAS AS PS ON PT.PIZZA_TYPE_ID = PS.PIZZA_TYPE_ID
GROUP BY
	PT.NAME
ORDER BY
	MAX(PS.PRICE) DESC
LIMIT
	1;

-- Identify the most common pizza size ordered.
SELECT
	PIZZAS.SIZE,
	COUNT(ORDER_DETAILS.ORDER_DETAILS_ID) AS TOTAL_ORDERS
FROM
	PIZZAS
	JOIN ORDER_DETAILS ON PIZZAS.PIZZA_ID = ORDER_DETAILS.PIZZA_ID
GROUP BY
	PIZZAS.SIZE
ORDER BY
	TOTAL_ORDERS DESC
LIMIT
	2;

-- List the top 5 most ordered pizza types along with their quantities.
SELECT
	PIZZA_TYPES.NAME,
	SUM(ORDER_DETAILS.QUANTITY) AS TOTAL_MOST_ORDER
FROM
	ORDER_DETAILS
	JOIN PIZZAS ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
	JOIN PIZZA_TYPES ON PIZZAS.PIZZA_TYPE_ID = PIZZA_TYPES.PIZZA_TYPE_ID
GROUP BY
	PIZZA_TYPES.NAME
ORDER BY
	TOTAL_MOST_ORDER DESC
LIMIT
	5;

-- Join the necessary tables to find the total quantity of each pizza category ordered.
SELECT
	CATEGORY,
	COUNT(NAME)
FROM
	PIZZA_TYPES
GROUP BY
	CATEGORY
ORDER BY
	COUNT(NAME) DESC;

-- Determine the distribution of orders by hour of the day.
SELECT
	EXTRACT(
		HOUR
		FROM
			TIME
	) AS HOURS,
	COUNT(ORDER_ID) AS ORDER_BY_HOURS
FROM
	ORDERS
GROUP BY
	HOURS
ORDER BY
	ORDER_BY_HOURS DESC;

-- Join relevant tables to find the category-wise distribution of pizzas.
SELECT
	PT.CATEGORY,
	SUM(OD.QUANTITY) AS DISTRIBUTION
FROM
	ORDER_DETAILS AS OD
	JOIN PIZZAS AS P ON OD.PIZZA_ID = P.PIZZA_ID
	JOIN PIZZA_TYPES AS PT ON P.PIZZA_TYPE_ID = PT.PIZZA_TYPE_ID
GROUP BY
	PT.CATEGORY
ORDER BY
	DISTRIBUTION DESC;

-- Group the orders by date and calculate the average number of pizzas ordered per day.
SELECT
	ROUND(AVG(PLACED_PZ), 2) AS AVG_DIST_PIZZA_PER_DAY
FROM
	(
		SELECT
			O.DATE,
			SUM(OD.QUANTITY) AS PLACED_PZ
		FROM
			ORDER_DETAILS AS OD
			JOIN ORDERS AS O ON OD.ORDER_ID = O.ORDER_ID
		GROUP BY
			O.DATE
		ORDER BY
			PLACED_PZ
	) AS AVG_VALUE;

-- Determine the top 3 most ordered pizza types based on revenue.
SELECT
	PT.NAME,
	SUM(P.PRICE * OD.QUANTITY) AS REVENUE
FROM
	ORDER_DETAILS AS OD
	JOIN PIZZAS AS P ON OD.PIZZA_ID = P.PIZZA_ID
	JOIN PIZZA_TYPES AS PT ON P.PIZZA_TYPE_ID = PT.PIZZA_TYPE_ID
GROUP BY
	PT.NAME
ORDER BY
	REVENUE DESC
LIMIT
	3;

-- Calculate the percentage contribution of each pizza type to total revenue.
WITH
	PIZZA_REVENUE AS (
		SELECT
			PT.CATEGORY,
			SUM(P.PRICE * OD.QUANTITY) AS PER_CATEGORY_REVENUE
		FROM
			ORDER_DETAILS AS OD
			JOIN PIZZAS AS P ON OD.PIZZA_ID = P.PIZZA_ID
			JOIN PIZZA_TYPES AS PT ON P.PIZZA_TYPE_ID = PT.PIZZA_TYPE_ID
		GROUP BY
			PT.CATEGORY
	),
	TOTAL_REVENUE AS (
		SELECT
			SUM(OD.QUANTITY * P.PRICE) AS TOTAL_SALES
		FROM
			ORDER_DETAILS AS OD
			JOIN PIZZAS AS P ON OD.PIZZA_ID = P.PIZZA_ID
	)
SELECT
	CTPR.CATEGORY,
	ROUND(CTPR.PER_CATEGORY_REVENUE, 2) AS CATEGORY_VISE_REVENUE,
	ROUND(CTTR.TOTAL_SALES, 2) AS TOTAL_REVENUE,
	(
		ROUND(
			CTPR.PER_CATEGORY_REVENUE * 100 / CTTR.TOTAL_SALES,
			2
		)
	)::TEXT || '%' AS PERSENTAGE_REVENUE
FROM
	PIZZA_REVENUE AS CTPR
	CROSS JOIN TOTAL_REVENUE AS CTTR;

-- Analyze the cumulative revenue generated over time.
SELECT
	DATE,
	SALES_BY_TIME,
	SUM(SALES_BY_TIME) OVER (
		ORDER BY
			DATE
	) AS COMULATIVE_REVNUE
FROM
	(
		SELECT
			O.DATE,
			SUM(OD.QUANTITY * P.PRICE) AS SALES_BY_TIME
		FROM
			ORDER_DETAILS AS OD
			JOIN PIZZAS AS P ON OD.PIZZA_ID = P.PIZZA_ID
			JOIN ORDERS AS O ON OD.ORDER_ID = O.ORDER_ID
		GROUP BY
			O.DATE
		ORDER BY
			O.DATE
	);

-- Determine the top 3 most ordered pizza types based on revenue for each pizza category.
WITH
	TR AS (
		SELECT
			PT.NAME,
			PT.CATEGORY,
			SUM(P.PRICE * OD.QUANTITY) AS PER_CATEGORY_REVENUE
		FROM
			ORDER_DETAILS AS OD
			JOIN PIZZAS AS P ON OD.PIZZA_ID = P.PIZZA_ID
			JOIN PIZZA_TYPES AS PT ON P.PIZZA_TYPE_ID = PT.PIZZA_TYPE_ID
		GROUP BY
			PT.CATEGORY,
			PT.NAME
	),
	RANK_TABLE AS (
		SELECT
			NAME,
			CATEGORY,
			PER_CATEGORY_REVENUE,
			RANK() OVER (
				PARTITION BY
					CATEGORY
				ORDER BY
					PER_CATEGORY_REVENUE DESC
			) AS RANKING_BY_REV_CATE
		FROM
			TR
	)
SELECT
	NAME,
	CATEGORY,
	PER_CATEGORY_REVENUE
FROM
	RANK_TABLE
WHERE
	RANKING_BY_REV_CATE <= 3
ORDER BY
	CATEGORY,
	PER_CATEGORY_REVENUE DESC;